version: "3.8"
services:
  mysql:
    image: mysql:8.0.19
    hostname: mysql
    container_name: mysql
    entrypoint: [ 'docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password' ]
    environment:
      MYSQL_DATABASE: alineacion
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_password
    ports:
      - "3307:3306"
#    networks:
#      - mysql
    volumes:
      - ./mysql_data:/var/lib/mysql #hot reloading
#  alineacion:
#    depends_on:
#      - mysql
#    build: .
#    image: alineacion
#    ports:
#      - "8081:8080"
##    networks:
##      - mysql
#    environment:
#      SPRING_APPLICATION_JSON: '{
#              "spring.datasource.url"  : "jdbc:mysql://mysql:3306/alineacion?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false",
#              "spring.datasource.username" : "my_user",
#              "spring.datasource.password" : "my_password"
#            }'
#    links:
#      - mysql:mysql
##networks:
##  mysql:
##    driver: bridge